name: Genarate ASCII key
on: push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        
        - name: checkout repo files
          run: ls
          
        - name: Run the shell script
          run: ./ascii_script.sh
          
       

        

