name: Genarate ASCII key
on: push
jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Install Cowsay Program
         # uses: actions/checkout@v4
          run: sudo apt-get install cowsay -y
        
        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run for cover, I am a DRAGON.....RAWR" >> dragon.txt
         
        - name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: dragon-text-file
            path: dragon.txt
            if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps: 
        - name: Download Artifacts
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file
            
  
        - name: Test file exists
          run: grep -i "dragon" dragon.txt
          
    deploy_job_3:
        needs: [test_job_2]
        runs-on: ubuntu-latest
        steps:
        - name: Download Artifacts
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file

        - name: Read file
          run: cat dragon.txt
        - name: Deploy
          run: echo Deploying.. .. . ..


       # - name: Run the shell script
        #  run: |
         #   chmod a+x ascii-script.sh
          #  ./ascii-script.sh
          
       

        

