  name: First Actions workflow
  on: push
  jobs: 
      first_job:
        runs-on: ubuntu-latest
        steps:
          - name: welcome to first lab
            run: echo "my frist github actions"
          - name: list files
            run: ls
          - name: read file
            run: cat README.md
  