  name: First Actions workflow
  on: push
  jobs: 
      first_job:
        runs-on: ubuntu-latest
        steps:
          - name: checkout repo
            uses: actions/checkout@v4

          - name: welcome to first lab
            run: |
                 echo "my frist github actions"
                 ls -ltra
                 cat README.md

          - name: generate asci key 
            run: Cowsay -f dragon "RUN for cover, I'm Dragon ..RAW" >> drgaon.txt
  