
name: Matrix Configuration

on:
    push:
    workflow_dispatch: 

jobs:
    deploy-on-ubuntu:
        runs-on: ubuntu-latest
        steps:
        - name: Echo Docker details
          run: docker info

        - name: Run Images 
          run: docker run hello-word
    
    deploy-on-windows:
        runs-on: windows-latest
        steps:
        - name: Echo Docker details
          run: docker info
        - name: Run Images
          run: docker run hello-word