name: Exploring variables and secrets

on: 
    push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: suribabu
    IMAGE_NAME: github-actions-nginx

jobs:
    docker:
        
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          run: docker build -t ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:lastest

        - name: Docker Login
          env:
            DOCKER_PASSWORD: s3cUrePaSsw0rd
          run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

        - name: Docker Publish
          run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    
    Deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
        - name: Docker Run
          run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest